# 机器学习中 距离计算

In [11]:
import numpy as np
import math

## 1. 欧式距离(Euclidean)
    # 11. 多维空间内的点和点之间几何距离
    # 22. 传入参数为两个向量，返回值为欧式距离
    # 33. 代码具有多种实现方式

In [7]:
def Euclidean(vecA, vecB, way):
    if way == 0 :
        return math.sqrt(((npvecA-npvecB)**2).sum())
    elif way == 1 :
        return sqrt((vector1-vector2)*((vector1-vector2).T))
    else:
        print ('请选择计算方式！')

# 2. 曼哈顿距离(Manhattan)
    # 欧式距离是直线距离，曼哈顿距离是折线距离

In [6]:
def Manhattan(vecA, vecB):
    
    return np.abs(npvecA-npvecB).sum()

3

# 3. 切比雪夫距离(Chebyshev)
    # 用于在多维空间中，将对象从某个位置移动到另外一个对象所消耗的最小距离

In [ ]:
def Chebyshev(vec1, vec2):
    
    return max(np.abs(npvec1-npvec2))

# 4. 闵可夫斯基(Minkowski)
        # 1. 距离最常用的 p 是 2 和 1, 前者是欧几里得距离（Euclidean distance），后者是曼哈顿距离
        # 2. 当 p 趋近于无穷大时，闵可夫斯基距离转化成切比雪夫距离

In [ ]:
x=np.random.random(5)
y=np.random.random(5)

#方法一：根据公式求解,p=2
print (np.sqrt(np.sum(np.square(x-y))))

#方法二：根据scipy库求解
from scipy.spatial.distance import pdist
X=np.vstack([x,y])
print (pdist(X,'minkowski',p=2))

# 4. 马氏距离(Mahalanobis)

## 表示数据的协方差距离，是一种有效的计算两个未知样本集的相似度的方法
## 马氏距离要求样本数要大于维数，否则无法求协方差矩阵

In [72]:

# 转置，表示10个样本，每个样本2维
X=np.vstack([np.random.random(10), np.random.random(10)])
XT=X.T

# 方法一：根据公式求解
S=np.cov(X)   # 两个维度之间协方差矩阵
SI = np.linalg.inv(S) # 协方差矩阵的逆矩阵

# 马氏距离计算两个样本之间的距离，此处共有10个样本，两两组合，共有45个距离。
n=XT.shape[0]
d1=[]
for i in range(0,n):
    for j in range(i+1,n):
        delta=XT[i]-XT[j]
        d=np.sqrt(np.dot(np.dot(delta,SI),delta.T))
        d1.append(d)
        
# 方法二：根据scipy库求解
from scipy.spatial.distance import pdist
d2=pdist(XT,'mahalanobis')

In [79]:
print (d1)
print (d2)

[1.2235931588364666, 0.82366053652190385, 2.1121190349537278, 1.1638532203683336, 1.2135789857980777, 1.9916281220343783, 1.4282225217803972, 1.0209619292247298, 2.6399977655985141, 0.51763536010143008, 3.2066843935127234, 2.3800993475771794, 2.0177326240798719, 2.2552971937952244, 2.6517431908092517, 0.91760753042417542, 2.8438974668468999, 2.9171866680633789, 1.9308971526410643, 1.8580584141891734, 2.3368581717948995, 2.2211261546511429, 1.0187409408652506, 2.9679230676744877, 1.4743568956551674, 1.3174836617161736, 2.0925456446838697, 1.2258067336319873, 2.4943795729195957, 2.4250209448648854, 1.4842049565969677, 2.5294944120867062, 0.32160251594317396, 2.0650309845856452, 3.1047309326874033, 1.0498994130437895, 1.5083160348117903, 1.2045194607083367, 1.6251656963933432, 2.5555801789185635, 1.3490756948065694, 0.6498027028966088, 2.2572400864810258, 3.0924770042695893, 1.9617670093974495]
[ 1.22359316  0.82366054  2.11211903  1.16385322  1.21357899  1.99162812
  1.42822252  1.020961

In [71]:
n=XT.shape[0]
for i in range(0,n):
    for j in range(i+1,n):
        print (XT[i])
        print (XT[j])
        delta=XT[i]-XT[j]
        print ('--------')
        print (delta)
        break

[ 0.48718151  0.9888734 ]
[ 0.25107299  0.40016103]
--------
[ 0.23610852  0.58871236]
[ 0.25107299  0.40016103]
[ 0.53436156  0.15068729]
--------
[-0.28328857  0.24947374]
[ 0.53436156  0.15068729]
[ 0.27438423  0.32450102]
--------
[ 0.25997733 -0.17381373]
[ 0.27438423  0.32450102]
[ 0.14249925  0.66702626]
--------
[ 0.13188499 -0.34252524]
[ 0.14249925  0.66702626]
[ 0.8364992   0.28387395]
--------
[-0.69399995  0.38315232]
[ 0.8364992   0.28387395]
[ 0.6463512   0.60372953]
--------
[ 0.190148   -0.31985558]
[ 0.6463512   0.60372953]
[ 0.76219307  0.00768451]
--------
[-0.11584187  0.59604502]
[ 0.76219307  0.00768451]
[ 0.30117686  0.15284347]
--------
[ 0.4610162  -0.14515896]
[ 0.30117686  0.15284347]
[ 0.73310728  0.09928858]
--------
[-0.43193041  0.05355489]


In [35]:
vecA = [0, 1, 0]
vecB = [0, 0, 2]

npvecA, npvecB = np.array(vecA), np.array(vecB)

npvec = np.array([npvecA, npvecB])

print (npvec)

sub = npvec.T[0]-npvec.T[1]

print (sub)
inv_sub = np.linalg.inv(np.cov(npvecA, npvecB))

print (inv_sub)
print (math.sqrt(np.dot(inv_sub, sub).dot(sub.T)))

[[0 1 0]
 [0 0 2]]
[-1  0]
[[ 4.  1.]
 [ 1.  1.]]
2.0


In [45]:
sub

array([-1,  0])

In [44]:
help(np.linalg.inv)

Help on function inv in module numpy.linalg.linalg:

inv(a)
    Compute the (multiplicative) inverse of a matrix.
    
    Given a square matrix `a`, return the matrix `ainv` satisfying
    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Matrix to be inverted.
    
    Returns
    -------
    ainv : (..., M, M) ndarray or matrix
        (Multiplicative) inverse of the matrix `a`.
    
    Raises
    ------
    LinAlgError
        If `a` is not square or inversion fails.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    Examples
    --------
    >>> from numpy.linalg import inv
    >>> a = np.array([[1., 2.], [3., 4.]])
    >>> ainv = inv(a)
    >>> np.allclose(np.dot(a, ainv), np.eye(2))
    True
    >>> np.allclose(np.dot(ainv, a), np.eye(2))
    True
    
    If a is a matrix object, then the return valu

In [39]:
np.cov(npvecA, npvecB)

array([[ 0.33333333, -0.33333333],
       [-0.33333333,  1.33333333]])

In [38]:
sub

array([-1,  0])

In [37]:
npvec.T[1]

array([1, 0])

In [36]:
npvec.T[0]

array([0, 0])

# 各函数测试结果

In [33]:
vecA = [0, 1, 0]
vecB = [0, 0, 2]

npvecA, npvecB = np.array(vecA), np.array(vecB)

euclidean = Euclidean(npvecA, npvecB)
print (euclidean)

manhattan = Manhattan(npvecA, npvecB)
print (manhattan)

mahalanobis = Mahalanobis(npvecA, npvecB)
print (mahalanobis)

2.23606797749979
3
2.0
